name: Frontegg Android SDK

on:
  push:
    branches-ignore:
      - master
env:
  CI: true
  LANG: en_US.UTF-8

concurrency:
  group: ci-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          server-id: ossrh
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          cache: 'gradle'
          distribution: temurin
      - name: Build Libraries
        run: ./gradlew build --no-daemon
#      - name: prepare release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
#          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
#        run: ./gradlew publish