name: Push Workflow

on:
  push:
    branches-ignore:
      - 'master'
      - 'release/next'
env:
  CI: true
  LANG: en_US.UTF-8

concurrency:
  group: ci-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build And Test
    runs-on: macos-latest-xl
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Libraries
        shell: bash
        run: ./gradlew :app:build --no-daemon

      - name: Set Alpha Version
        id: incremented-alpha-version
        uses: ./.github/actions/update-gradle-version
        with:
          type: alpha

      - name: prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: ./gradlew publish --no-daemon --no-parallel

